### PR TITLE
Add a basic settings page for OneLogin

### PR DESCRIPTION
**Pull request by scottmckenzie**
This is my attempt at a settings page for this plugin.  It only supports the OneLogin (internal) connection_type and providing the certificate via hash.

It includes two new classes files:
* inc/class-wp-saml-auth-settings.php - creates the settings page in the Wordpress dashboard
* inc/class-wp-saml-auth-options.php - loads the settings from the Wordpress database and overrides the default optionss configured via wpsa_filter_option

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks for the pull request, @scottmckenzie 

Are you open to spending some time iterating on it? There are a couple of things I'd like to see in the settings page before it lands:

1. All of the relevant OneLogin and general settings should be editable. It's fine that SimpleSAMLphp configuration is only accessible through the filter.
2. When there is a filter in place, its values should display on the settings page in read-only mode (because the filter should always take priority over the settings page).

**Comment by scottmckenzie** [comment]
Hi @danielbachhuber 

I'm happy to make whatever changes you deem necessary.  

1.  Which specific OneLogin settings do you want to edit?  All of the ones in https://github.com/onelogin/php-saml/blob/master/settings_example.php?  What about the advanced settings (https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php)?
I thought I had added all of the default options added by the wpsa_filter_option function.  Looks like **strict** is missing. I didn't bother adding the bindings because the OneLogin doco says that it only supports HTTP-POST for the SP and HTTP-Redirect for the IdP.  Do you want the bindings to be editable?
2. I'll look in to this.

**Comment by danielbachhuber** [comment]
> 1. Which specific OneLogin settings do you want to edit? All of the ones in https://github.com/onelogin/php-saml/blob/master/settings_example.php? What about the advanced settings (https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php)?
I thought I had added all of the default options added by the wpsa_filter_option function. Looks like strict is missing. I didn't bother adding the bindings because the OneLogin doco says that it only supports HTTP-POST for the SP and HTTP-Redirect for the IdP. Do you want the bindings to be editable?

Sorry, to clarify, I was referring to all of the WP SAML Auth settings that aren't specific to SimpleSAMLphp (e.g. `auto_provision`, `permit_wp_login`, and `get_user_by`).

**Comment by scottmckenzie** [comment]
> Sorry, to clarify, I was referring to all of the WP SAML Auth settings that aren't specific to SimpleSAMLphp (e.g. `auto_provision`, `permit_wp_login`, and `get_user_by`).

Those options are configurable:
wp-saml-auth-settings

**Comment by scottmckenzie** [comment]
> 2. When there is a filter in place, its values should display on the settings page in read-only mode (because the filter should always take priority over the settings page).

Do you know how I can determine if there is a filter already in place?  I have a mu-plugin that is not detected by `has_filter('wp_saml_auth_option')`.  The first time has_filter returns true is after this line: https://github.com/pantheon-systems/wp-saml-auth/blob/497089e4e2559d01c2e2c7f383a2e9127cb7b260/wp-saml-auth.php#L160

**Comment by danielbachhuber** [comment]
> Those options are configurable:

Ah, great, thanks :)

> Do you know how I can determine if there is a filter already in place? I have a mu-plugin that is not detected by `has_filter('wp_saml_auth_option')`.

`has_filter()` should be sufficient. Can you give me a code example to reproduce?

**Comment by danielbachhuber** [comment]
Continuing on with this in #151

Thanks again for your work on it, @scottmckenzie

**Pull request closed without merging**
